config-version: 2

name: "jaffle_shop"
version: "0.1"
require-dbt-version: ">=1.5.0"

profile: "jaffle_shop"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["data-tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"
  - "logs"

vars:
  "dbt_date:time_zone": "America/New_York"

seeds:
  +schema: raw
  +docs:
    node_color: "#cd7f32"

models:
  jaffle_shop:
    marts:
      +tags: marts
      +materialized: table
    staging:
      +tags: staging
      +materialized: view
