version: '3'

vars:
  VENV_DIR: .venv
  DBT_PROFILES_DIR: "{{.PWD}}"

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  # Bootstrap tasks
  bootstrap:
    desc: Complete setup - create venv, install dependencies, and run dbt deps
    cmds:
      - task: sync
      - task: deps

  sync:
    desc: Sync Python dependencies using uv
    cmds:
      - uv sync
    sources:
      - pyproject.toml
      - uv.lock
    generates:
      - "{{.VENV_DIR}}/lib/python*/site-packages/**/*"

  sync-dev:
    desc: Sync Python dependencies including dev group
    cmds:
      - uv sync --group dev
    sources:
      - pyproject.toml
      - uv.lock

  install:
    desc: Install a package using uv
    cmds:
      - uv add {{.CLI_ARGS}}

  install-dev:
    desc: Install a dev package using uv
    cmds:
      - uv add --group dev {{.CLI_ARGS}}

  deps:
    desc: Install dbt dependencies (packages)
    deps: [sync]
    cmds:
      - uv run dbt deps --profiles-dir {{.DBT_PROFILES_DIR}}
    sources:
      - packages.yml
    generates:
      - dbt_packages/**/*

  # dbt commands
  debug:
    desc: Test database connection and show configuration
    deps: [sync]
    cmds:
      - uv run dbt debug --profiles-dir {{.DBT_PROFILES_DIR}}

  clean:
    desc: Clean dbt artifacts
    cmds:
      - uv run dbt clean --profiles-dir {{.DBT_PROFILES_DIR}}
      - rm -rf logs/

  seed:
    desc: Load seed data (CSV files)
    deps: [deps]
    cmds:
      - uv run dbt seed --profiles-dir {{.DBT_PROFILES_DIR}}

  run:
    desc: Run dbt models
    deps: [deps]
    cmds:
      - uv run dbt run --profiles-dir {{.DBT_PROFILES_DIR}} {{.CLI_ARGS}}

  test:
    desc: Run dbt tests
    deps: [deps]
    cmds:
      - uv run dbt test --profiles-dir {{.DBT_PROFILES_DIR}} {{.CLI_ARGS}}

  build:
    desc: Run seeds, models, snapshots and tests (full build)
    deps: [deps]
    cmds:
      - uv run dbt build --profiles-dir {{.DBT_PROFILES_DIR}} {{.CLI_ARGS}}

  snapshot:
    desc: Execute snapshots
    deps: [deps]
    cmds:
      - uv run dbt snapshot --profiles-dir {{.DBT_PROFILES_DIR}}

  compile:
    desc: Compile models without running them
    deps: [deps]
    cmds:
      - uv run dbt compile --profiles-dir {{.DBT_PROFILES_DIR}} {{.CLI_ARGS}}

  # Documentation
  docs:generate:
    desc: Generate dbt documentation
    deps: [deps]
    cmds:
      - uv run dbt docs generate --profiles-dir {{.DBT_PROFILES_DIR}}

  docs:serve:
    desc: Serve dbt documentation (opens in browser)
    deps: [docs:generate]
    cmds:
      - uv run dbt docs serve --profiles-dir {{.DBT_PROFILES_DIR}}

  docs:
    desc: Generate and serve dbt documentation
    cmds:
      - task: docs:generate
      - task: docs:serve

  # Development workflow
  dev:
    desc: Full development workflow - build and generate docs
    cmds:
      - task: build
      - task: docs:generate

  # Quick run commands
  run-model:
    desc: "Run a specific model (usage: task run-model -- -s model_name)"
    deps: [deps]
    cmds:
      - uv run dbt run --profiles-dir {{.DBT_PROFILES_DIR}} -s {{.CLI_ARGS}}

  test-model:
    desc: "Test a specific model (usage: task test-model -- -s model_name)"
    deps: [deps]
    cmds:
      - uv run dbt test --profiles-dir {{.DBT_PROFILES_DIR}} -s {{.CLI_ARGS}}

  # Utility tasks
  lint:
    desc: Lint SQL files with sqlfluff
    deps: [sync-dev]
    cmds:
      - uv run sqlfluff lint models/ --dialect duckdb

  lint-fix:
    desc: Lint and fix SQL files with sqlfluff
    deps: [sync-dev]
    cmds:
      - uv run sqlfluff fix models/ --dialect duckdb

  format:
    desc: Format SQL files with sqlfluff
    deps: [sync-dev]
    cmds:
      - uv run sqlfluff format models/ --dialect duckdb

  # Data exploration
  duckdb:
    desc: Open DuckDB CLI for the jaffle_shop database
    cmds:
      - duckdb data/jaffle_shop.duckdb

  # Cleanup tasks
  clean-all:
    desc: Remove all generated files and virtual environment
    cmds:
      - task: clean
      - rm -rf {{.VENV_DIR}}
      - rm -rf dbt_packages/
      - rm -rf data/jaffle_shop.duckdb
      - rm -rf data/jaffle_shop.duckdb.wal

  # Fresh start
  fresh:
    desc: Clean everything and bootstrap from scratch
    cmds:
      - task: clean-all
      - task: bootstrap
      - task: build
